services:
  postgres:
    image: postgres:16 # Utilisation de l'image officielle PostgreSQL version 16
    ports:
      - 5432:5432 # Exposition du port PostgreSQL pour y accéder localement
    volumes:
      - ./postgres:/var/lib/postgresql/data # Stockage persistant des données
    environment:
      - POSTGRES_PASSWORD=password # Mot de passe pour l'utilisateur PostgreSQL
      - POSTGRES_USER=user # Nom de l'utilisateur PostgreSQL
      - POSTGRES_DB=db # Nom de la base de données PostgreSQL